CREATE TABLE IF NOT EXISTS buildings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name TEXT NOT NULL,
    address TEXT,
    city TEXT,
    description TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id BIGINT REFERENCES buildings(id),
    unit_number TEXT NOT NULL,
    property_type TEXT NOT NULL,
    bedrooms INTEGER DEFAULT 0,
    bathrooms INTEGER DEFAULT 1,
    monthly_rent NUMERIC(10,2) NOT NULL,
    security_deposit NUMERIC(10,2) DEFAULT 0,
    maximum_occupants INTEGER DEFAULT 1,
    description TEXT,
    status TEXT DEFAULT 'Available',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS property_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    caption TEXT,
    is_main BOOLEAN DEFAULT FALSE,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_reference TEXT UNIQUE NOT NULL,
    property_id BIGINT REFERENCES properties(id),
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    nationality TEXT,
    occupants INTEGER DEFAULT 1,
    requested_move_in DATE,
    rental_months INTEGER DEFAULT 12,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    property_id BIGINT REFERENCES properties(id),
    contract_start DATE,
    contract_end DATE,
    monthly_rent NUMERIC(10,2),
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rent_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES tenants(id),
    property_id BIGINT REFERENCES properties(id),
    rent_month DATE NOT NULL,
    due_date DATE NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    status TEXT DEFAULT 'Due',
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES tenants(id),
    application_id BIGINT REFERENCES applications(id),
    invoice_id BIGINT REFERENCES rent_invoices(id),
    amount NUMERIC(10,2) NOT NULL,
    payment_method TEXT DEFAULT 'Bank Transfer',
    bank_reference TEXT,
    receipt_url TEXT,
    status TEXT DEFAULT 'Pending Verification',
    verified_at TIMESTAMPTZ,
    verified_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_reference TEXT UNIQUE NOT NULL,
    tenant_id BIGINT REFERENCES tenants(id),
    property_id BIGINT REFERENCES properties(id),
    category TEXT NOT NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT DEFAULT 'Normal',
    status TEXT DEFAULT 'Open',
    assigned_to TEXT,
    resolution TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS complaint_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT REFERENCES complaints(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    author_role TEXT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS complaint_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT REFERENCES complaints(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS company_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT,
    bank_name TEXT,
    account_name TEXT,
    iban TEXT,
    currency TEXT DEFAULT 'QAR',
    phone TEXT,
    email TEXT
);

CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('tenant', 'manager')),
    full_name TEXT,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE tenants      ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE payments     ADD COLUMN IF NOT EXISTS transfer_date DATE;

CREATE UNIQUE INDEX IF NOT EXISTS ux_buildings_name   ON buildings (building_name);
CREATE UNIQUE INDEX IF NOT EXISTS ux_properties_unit  ON properties (building_id, unit_number);
CREATE UNIQUE INDEX IF NOT EXISTS ux_photos_prop_url  ON property_photos (property_id, image_url);
CREATE UNIQUE INDEX IF NOT EXISTS ux_invoice_month    ON rent_invoices (tenant_id, rent_month);
CREATE INDEX IF NOT EXISTS ix_tenants_user            ON tenants (user_id);
CREATE INDEX IF NOT EXISTS ix_applications_user       ON applications (user_id);

ALTER TABLE profiles              ENABLE ROW LEVEL SECURITY;
ALTER TABLE buildings             ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties            ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_photos       ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications          ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants               ENABLE ROW LEVEL SECURITY;
ALTER TABLE rent_invoices         ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments              ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints            ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_comments    ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_settings      ENABLE ROW LEVEL SECURITY;

INSERT INTO storage.buckets (id, name, public) VALUES ('property-images', 'property-images', true)
    ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('receipts', 'receipts', false)
    ON CONFLICT (id) DO NOTHING;

INSERT INTO company_settings (company_name, bank_name, account_name, iban, currency, phone, email)
SELECT 'My Property Company', 'QNB', 'My Property Company LLC', 'QA00XXXX0000000000000000000', 'QAR', '+97400000000', 'info@property.com'
WHERE NOT EXISTS (SELECT 1 FROM company_settings);

DELETE FROM auth.users WHERE id IN (SELECT id FROM profiles WHERE role = 'customer');
DELETE FROM profiles WHERE role = 'customer';
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('tenant', 'manager'));
